### DISCUSSION TITLE
Mixed Content Blocked when trying to add a link item

### DISCUSSION THREAD

**Discussion by frenicohansen** [JulianPrieber/littlelink-custom#286] [Questions]
Hi all,
I just deployed littlelink-custom using docker and just started to configure the site. But I got this error in Firefox's Console Log while trying to create a link item.
![image](https://user-images.githubusercontent.com/16384641/209550244-531e8f1c-4224-467e-ab00-22e7f7e58338.png)

`Blocked loading mixed active content “http://<site_url>/studio/linkparamform_part/1/0”.`

And these are the relevant configs.
![image](https://user-images.githubusercontent.com/16384641/209549930-870d188d-799e-4815-8775-d384815383f0.png)
![image](https://user-images.githubusercontent.com/16384641/209549951-8c6594ab-52b9-4784-97b5-962070361fb8.png)

**Comment by frenicohansen** [comment]
Fixed the issue using the configuration from https://github.com/JulianPrieber/llc-docker#nginx. But still can't manage to add a link item.
![image](https://user-images.githubusercontent.com/16384641/209551665-aa286c4d-2c0b-45c7-ba47-3ace66377f75.png)

When I entered the credentials and click the login button. I got redirected to https://<site_url>/login and got error 419.
![image](https://user-images.githubusercontent.com/16384641/209551735-c6534d78-e10f-4e64-8861-6c23a23c12ee.png)

**Comment by s4ros** [comment]
I got it working with `traefik` as a reverse proxy (I just prefer to use traefik when it comes to reverse proxying for docker containers).
Here is the `docker-compose.yml` for the LittleLink Custom that works:

```yml
version: '3.9'

volumes:
  llc:

networks:
  traefik:
    external: true

services:
  littlelink:
    image: julianprieber/littlelink-custom
    restart: unless-stopped
    container_name: littlelink
    expose:
      - 80
    environment:
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      SERVER_ADMIN: admin@admin.com
      TZ: Europe/Warsaw
      PHP_MEMORY_LIMIT: 1024M
      UPLOAD_MAX_FILESIZE: 32M
        #FORCE_ROUTE_HTTPS: true
    volumes:
      - llc:/htdocs
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.rule: Host(`example.com`)
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.certresolver: myresolver
      traefik.http.middlewares.homepage.headers.contentsecuritypolicy: upgrade-insecure-requests
      traefik.http.routers.homepage.middlewares: homepage

```
And, if you shell be interested, I also include my traefik's docker-compose file

```yml
version: "3.9"

networks:
  traefik:
    name: traefik

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=admin@admin.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
```
