### DISCUSSION TITLE
after registered the new user, the website get crashed

### DISCUSSION THREAD

**Discussion by kingdov** [JulianPrieber/littlelink-custom#342] [Issues]
Illuminate\Contracts\Container\BindingResolutionException
Target class [] does not exist.
http://localhost:8888/littlelink-custom/studio/index

**Comment by JulianPrieber** [comment]
Any updates?
I'd need more details about your setup to be able to help you.

**Comment by Ti-Tom** [comment]
Same error with docker image (julianprieber/littlelink-custom:latest) when i try to access to studio pages (ex: /studio/add-link).

```
[previous exception] [object] (ReflectionException(code: -1): Class \"\" does not exist at /htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)
[stacktrace]
#0 /htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): ReflectionClass->__construct()
#1 /htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(758): Illuminate\\Container\\Container->build()
#2 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): Illuminate\\Container\\Container->resolve()
#3 /htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(694): Illuminate\\Foundation\\Application->resolve()
#4 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(836): Illuminate\\Container\\Container->make()
#5 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(206): Illuminate\\Foundation\\Application->make()
#6 /htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(180): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#7 /htdocs/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#8 {main}
"} 
```

**Reply by JulianPrieber** [reply]
I tested this on the latest docker version without issues.
Are you running this behind a reverse proxy?

**Reply by Ti-Tom** [reply]
Yes, i'm using [nginx proxy manager](https://nginxproxymanager.com/) which forwards 443 to 8888.
And docker bind only 443 to 8888.
I'm not using port 80 from image.

Note: i try adding this in npm conf (from llc-docker README) but i have the same error
```
location / {
    # Replace with the IP address and port number of your Docker container.
    proxy_pass https://$server:8888; # $server = IP
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-VerifiedViaNginx yes;
    proxy_read_timeout 60;
    proxy_connect_timeout 60;
    proxy_redirect off;

    # Specific for websockets: force the use of HTTP/1.1 and set the Upgrade header
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Fixes Mixed Content errors.
    add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
}
```

**Reply by JulianPrieber** [reply]
Have you tried accessing your instance over port 8888 directly to see if the error persists?

**Reply by Ti-Tom** [reply]
Same error and it work perfectly for all panel routes (ex: panel/config).

**Reply by JulianPrieber** [reply]
Are you accessioning the instance over HTTP or HTTPS? What browser are you using?
(When using port 8888 directly)

**Reply by Ti-Tom** [reply]
HTTPS, if i try over HTTP, i have this error:
```
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
```

And i force all queries to used HTTPS: `FORCE_HTTPS=true`.
And proxy redirect all HTTP to HTTPS.

I'm using Firefox (110.0.1) and i try with Chrome (110.0.5481.177) / Microsoft Edge (110.0.1587.63) on Ubuntu.

**Reply by JulianPrieber** [reply]
I tried to reproduce your exact setup and cannot get any error messages to show.

Could you describe your setup process, how did you set up your docker image?
Does this happen when setting up a new docker image and leaving everything as the default settings?

**Reply by Ti-Tom** [reply]
Here my docker-compose.yml (`docker compose up -d`) & mysql is host on another server.

```
version: '3'
services:
  littlelink:
    image: julianprieber/littlelink-custom:latest
    ports:
      - "8888:443"
    environment:
      SERVER_ADMIN: admin@domain.com
      HTTP_SERVER_NAME: domain.com
      HTTPS_SERVER_NAME: domain.com
      TZ: Europe/Paris
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
      LOG_LEVEL: 'info'
    restart: always
    volumes:
      - './config/.env:/htdocs/.env:rw'
      - './config/advanced-config.php:/htdocs/config/advanced-config.php:rw'
      - './config/img:/htdocs/img:rw'
```

[/config/.env](https://github.com/JulianPrieber/littlelink-custom/files/10882558/env.txt)
and advanced-config.php is the similar as the one in the repository.
