### ISSUE TITLE
Documentation : Traefik

### ISSUE THREAD

**Issue by egooner** [JulianPrieber/littlelink-custom#209]
Thanks for the doc on Nginx reverse proxy.

I used it to get my traefik proxy working ... You might want to include some details for that too this is what I added to get mine working

http:
  routers:
    container_name:
      entryPoints:
        - websecure
      rule: "Host(`fqdn of container`)"
      middlewares:
        [container_name-Header]
      service: container_name
      tls: {}
  middlewares:
    container_name-Header:
      headers:
        contentSecurityPolicy: upgrade-insecure-requests
  services:
    container_name:
      loadBalancer:
        servers:
          - url: http://container_name

**Comment by JulianPrieber** [comment]
WIP: https://github.com/LittleLink-Custom/docs

https://github.com/JulianPrieber/llc-docker/pull/30

**Comment by Leopere** [comment]
Yeah this doesen't seem fixed I tried deploying this and it seems that despite having a websecure tls upgrade middleware in Traefik I'm getting alll sorts of http connection attempts instead of https 
<img width="440" alt="image" src="https://github.com/LinkStackOrg/LinkStack/assets/1068374/c943440b-b474-4191-b069-767a62fc0ffc">

**Comment by Leopere** [comment]
It would appear that in your environment section you require "FORCE_HTTPS=true"

**Comment by Leopere** [comment]
`~/linkstack|⇒  cat linkstack.yml`
```yaml
version: "3"
services:
  linkstack:
    image: linkstackorg/linkstack
    environment:
      SERVER_ADMIN: user@example.com
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      FORCE_HTTPS: "true"
      PHP_MEMORY_LIMIT: 512M
      UPLOAD_MAX_FILESIZE: 8M
#    volumes:
#      - /mnt/tank/persist/example.com/linkstack/production/data:/htdocs
    deploy:
      replicas: 1
      labels:
        - "us.nixc.autodeploy=true"
        - "traefik.enable=true"
        - "traefik.http.routers.linkstack_linkstack.tls=true"
        - "traefik.http.services.linkstack_linkstack.loadbalancer.server.port=80"
        - "traefik.http.routers.linkstack_linkstack.rule=Host(`example.com`)"
        - "traefik.http.routers.linkstack_linkstack.entrypoints=websecure"
        - "traefik.http.routers.linkstack_linkstack.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.linkstack_linkstack.service=linkstack_linkstack"
        - "traefik.docker.network=traefik"
    networks:
      - traefik
networks:
  traefik:
    external: true
```

**Comment by JulianPrieber** [comment]
You need to upgrade all requests to https

**Comment by Leopere** [comment]
> You need to upgrade all requests to https

The websecure middleware should already be doing this.

**Comment by JulianPrieber** [comment]
Apparently not

**Comment by Leopere** [comment]
```yaml
version: "3.7"

x-command: &command
    command:
      # Docker swarm configuration
#      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Writing Logs to a File, in JSON
      - "--log.filePath=/traefik.log"
      - "--log.format=json"
#      - "--log.level=DEBUG"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--providers.docker.endpoint=http://socketproxy_socketproxy:2375"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      # Configure entrypoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
#      - "--entrypoints.websecure.http.middlewares=crowdsec-bouncer, globalerror"
#      ## Enable this to allow access to endpoints through Authelia rather than defining all authelia participants through labels.
#      - "--entrypoints.websecure.http.middlewares=crowdsec-bouncer, globalerror, authelia"
#      - "--entrypoints.websecure.http.middlewares=globalerror, crowdsec-bouncer"
#      - "--entrypoints.websecure.http.middlewares=globalerror"
      # SSL configuration
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencryptresolver.acme.email=admin@nixc.us"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      # Global HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Enable dashboard
      - "--api.dashboard=true"
      ```
